### ISSUE TITLE
[TASK] App should be responsive

### ISSUE THREAD

**Issue by amitojsingh** [KhalisFoundation/gurmukhi-web#104]

**Comment by MySmilingTurban** [comment]
@amitojsingh veerji, please have a look at this
Can be reproduced on information page of any word or simply going to random word page

<img width="426" alt="Screenshot 2024-03-12 at 10 41 22 am" src="https://github.com/KhalisFoundation/gurmukhi-web/assets/51584037/8c43158c-3c76-4889-bf26-276df85fa715">

**Comment by MySmilingTurban** [comment]
fixed
