### ISSUE TITLE
Add eslint styling

### ISSUE THREAD

**Issue by amitojsingh** [KhalisFoundation/gurmukhi-web#18]

**Comment by amitojsingh** [comment]
@MySmilingTurban Veer ji, are you working on this?

**Comment by MySmilingTurban** [comment]
> @MySmilingTurban Veer ji, are you working on this?

Hnji veerji

**Comment by amitojsingh** [comment]
Han ji veer ji I started but then I saw your PR. So, let me know if it’s completed?
