### ISSUE TITLE
[BUG] /question Invalid collection reference. Collection references must have an odd number of segments, but users/words has 2.

### ISSUE THREAD

**Issue by amitojsingh** [KhalisFoundation/gurmukhi-web#208]
The GetNewWord function gets an empty UID. 
Link to Bugsnag: https://app.bugsnag.com/khalis-foundation-1/shabadavali-dev/errors/6660207f613e3c0008cc22ae?filters[error.status]=open&filters[event.since]=30d&filters[user.id]=owtaNADFV3aVN6VYc3vUAnV04dk1&pivot_tab=event

**Comment by MySmilingTurban** [comment]
I think we can try storing uid in redux state to avoid this
