### ISSUE TITLE
[BUG] Sign In With Google not resetting the Redux State Game Progress and coins. 

### ISSUE THREAD

**Issue by amitojsingh** [KhalisFoundation/gurmukhi-web#232]
To Regenerate. 
1. login using username and password. Get a coin. 
2. Log out. 
3. Log in with sign-in with Google. It's still showing the same coins and the same Progress.

**Comment by MySmilingTurban** [comment]
unable to reproduce

**Comment by Gauravjeetsingh** [comment]
Is this still an issue, its working fine on my local.

**Comment by amitojsingh** [comment]
@Gauravjeetsingh Veer ji Han ji it's still an issue with the new Google Sign In User.  I have attached the PR in this thread. we will test once it's merge.
