### ISSUE TITLE
[BUG] Got first session again after sign in

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/gurmukhi-web#238]
**Describe the bug**
Got the first session again, after having done 4 sessions already on previous day

**To Reproduce**
1. sign in to existing account with google
2. Click on Start learning
3. I have already completed 4 yesterday but got the very first session again on clicking the play button
4. After completing that session, the words learnt increased by 2, but there were no new words in it.

**Comment by amitojsingh** [comment]
@Gauravjeetsingh Veer ji which email did you used?

**Comment by amitojsingh** [comment]
This is fixed veer ji.
