### ISSUE TITLE
Bugs in Dark Theme

### ISSUE THREAD

**Issue by amitojsingh** [KhalisFoundation/gurmukhi-web#32]
**Describe the bug**
The background is missing I see black in the background.

**Screenshots**

![Screenshot 2023-12-13 at 2 43 47 PM](https://github.com/KhalisFoundation/gurmukhi-web/assets/3595397/06d794d7-5198-424f-99de-550f5a527f82)

**Comment by MySmilingTurban** [comment]
Disable dark mode and it'll be fine
@amitojsingh

**Comment by amitojsingh** [comment]
It worked. I think we still have to manage dark mode and light mode.
